name: 'Healthy Notify'
description: 'Notification action for healthy repository'
author: 'mswnlz'
inputs:
  message:
    description: 'The message to print'
    required: false
    default: 'Hello from Healthy Action!'
runs:
  using: 'node20'
  main: 'index.js'
